# This file was generated by GoReleaser. DO NOT EDIT.
cask "infraspec" do
  name "infraspec"
  desc "Test your cloud infrastructure in plain English, no code required."
  homepage "https://infraspec.sh"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "infraspec"

  on_macos do
    on_intel do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_darwin_amd64.tar.gz"
      sha256 "ef6c6d2c14550fa5f150541e2e1589895f8bbf3425b21eec333e43ffb339ee40"
    end
    on_arm do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_darwin_arm64.tar.gz"
      sha256 "fa674591f2735ec6ee67aee49c66abb3abdf2a594e84633df1c37a3c52c76db1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_linux_amd64.tar.gz"
      sha256 "f4fd7509ed8f4a5bf367721cbfd7f93b57345e8e5557ac8232feaf842d427588"
    end
    on_arm do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_linux_arm64.tar.gz"
      sha256 "44febf4f71d8d452e66c21e1c36ab377e55544b0c3be89db00617f16882ffb80"
    end
  end

  # No zap stanza required
end
