# This file was generated by GoReleaser. DO NOT EDIT.
cask "infraspec" do
  name "infraspec"
  desc "Test your cloud infrastructure in plain English, no code required."
  homepage "https://infraspec.sh"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "infraspec"

  on_macos do
    on_intel do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_darwin_amd64.tar.gz"
      sha256 "5d6dc6ce59ce804957b911e7268130fc4e3c9bb6c7fff67bfd604edc697165d4"
    end
    on_arm do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_darwin_arm64.tar.gz"
      sha256 "1cdc7e7d882037001ae6f2c4054bffd259090982a70a554333a67c7d1401b785"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_linux_amd64.tar.gz"
      sha256 "8a6bd658431929e6d3f9966c69ec2e647b625f97654101d3c35b5f43784b7181"
    end
    on_arm do
      url "https://github.com/robmorgan/infraspec/releases/download/v#{version}/infraspec_#{version}_linux_arm64.tar.gz"
      sha256 "e8c3c2cb1ed733a7caf4432a5589383454505c4fc2f09e9aa236ce626242f1a9"
    end
  end

  # No zap stanza required
end
